"""Pi's searchable selectors: model/thinking selector, search input, list.

``tests/fixtures/pi_selectors/renders.json`` holds rows rendered by Pi's own
``ModelSelectorComponent`` / ``ThinkingSelectorComponent`` (pi-mono
``1b347794e``, generated by ``render.mts`` beside it) at width 80; pipy's rows
must match them as text.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from pipy_harness.native.chrome import ChromeStyle
from pipy_harness.native.keybindings import KeybindingsManager
from pipy_harness.native.overlay_state import OverlayState
from pipy_harness.native.ui.components.search_input import SearchInput
from pipy_harness.native.ui.components.search_selectors import (
    ModelChoice,
    ModelSearchSelector,
    SearchSelectorClose,
    ThinkingSearchSelector,
    model_search_text,
    model_selector_search_text,
    search_selector_keys,
    search_selector_region_lines,
)
from pipy_harness.native.ui.components.select_list import SelectItem, SelectList

_PI_RENDERS = json.loads(
    (Path(__file__).parent / "fixtures" / "pi_selectors" / "renders.json").read_text(
        encoding="utf-8"
    )
)
_SGR = re.compile(r"\x1b\[[0-9;]*m")
_PLAIN = ChromeStyle(enabled=False)
_COLOR = ChromeStyle(enabled=True, truecolor=True)

_MODELS = [
    ModelChoice("openai", "gpt-5.5", "GPT-5.5"),
    ModelChoice("anthropic", "claude-sonnet-4-5", "Claude Sonnet 4.5"),
    ModelChoice("openai-codex", "gpt-6.1-sol", "GPT-6.1 Sol"),
    ModelChoice("anthropic", "claude-opus-4-5", "Claude Opus 4.5"),
    ModelChoice("openrouter", "openai/gpt-5.5", "OpenAI: GPT-5.5"),
    ModelChoice("openai", "gpt-4o", "GPT-4o"),
]


def _pi_lines(name: str) -> list[str]:
    lines = [line.rstrip() for line in _PI_RENDERS[name]]
    refreshing = "  Refreshing model catalogs…"
    if refreshing in lines:
        index = lines.index(refreshing)
        del lines[index - 1 : index + 1]
    return lines


def _text(lines: list[str]) -> list[str]:
    return [_SGR.sub("", line).rstrip() for line in lines]


def _model_selector(
    *,
    scoped: list[ModelChoice] | None = None,
    search: str = "",
    manager: KeybindingsManager | None = None,
) -> ModelSearchSelector:
    return ModelSearchSelector(
        models=_MODELS,
        scoped_models=scoped or [],
        current=_MODELS[2],
        default=_MODELS[3],
        keys=search_selector_keys("app.models.save", manager),
        initial_search=search,
    )


def _thinking_selector() -> ThinkingSearchSelector:
    return ThinkingSearchSelector(
        levels=["off", "minimal", "low", "medium", "high", "xhigh"],
        current="high",
        default="medium",
        keys=search_selector_keys("app.thinking.save", None),
    )


def _feed(
    selector: ModelSearchSelector | ThinkingSearchSelector, keys: list[str]
) -> SearchSelectorClose | None:
    closed = None
    for key in keys:
        closed = selector.handle_key(key)
    return closed


@pytest.mark.parametrize(
    ("name", "scoped", "search", "keys"),
    [
        ("model_initial", [], "", []),
        ("model_search_gpt", [], "gpt", []),
        ("model_search_openai_gpt", [], "openai/gpt", []),
        ("model_search_def", [], "def", []),
        ("model_typed_down", [], "", ["o", "p", "u", "s", "down"]),
        ("model_none", [], "zzzz", []),
        ("model_scoped", [_MODELS[5], _MODELS[0]], "", []),
        ("model_scoped_tab", [_MODELS[5], _MODELS[0]], "", ["tab"]),
    ],
)
def test_model_selector_rows_match_pi(
    name: str, scoped: list[ModelChoice], search: str, keys: list[str]
) -> None:
    selector = _model_selector(scoped=scoped, search=search)
    _feed(selector, keys)
    assert _text(selector.render(80, _PLAIN)) == _pi_lines(name)


def test_thinking_selector_rows_match_pi() -> None:
    selector = _thinking_selector()
    assert _text(selector.render(80, _PLAIN)) == _pi_lines("thinking_initial")
    _feed(selector, ["h", "i"])
    assert _text(selector.render(80, _PLAIN)) == _pi_lines("thinking_hi")
    _feed(selector, ["backspace", "backspace", "z", "z", "z"])
    assert _text(selector.render(80, _PLAIN)) == _pi_lines("thinking_none")


def test_model_selector_colours_follow_pi_tokens() -> None:
    selector = _model_selector()
    lines = selector.render(80, _COLOR)
    border = "\x1b[38;2;95;168;204m"  # Pi dark `border`
    accent = "\x1b[38;2;167;152;215m"
    muted = "\x1b[38;2;157;165;169m"
    warning = "\x1b[38;2;205;154;34m"
    assert lines[0].startswith(border)
    assert lines[2].startswith(warning)
    assert lines[6] == (
        f"{accent}→ \x1b[0m{accent}✓ \x1b[0m{accent}gpt-6.1-sol\x1b[0m "
        f"{muted}[openai-codex]\x1b[0m"
    )
    # The search input's cursor cell is reverse video.
    assert "\x1b[7m \x1b[27m" in lines[4]


class TestModelSelectorKeys:
    def test_enter_selects_for_the_session(self) -> None:
        selector = _model_selector()
        assert _feed(selector, ["down", "enter"]) == SearchSelectorClose(_MODELS[3])

    def test_save_key_selects_as_default(self) -> None:
        selector = _model_selector()
        assert _feed(selector, ["ctrl-s"]) == SearchSelectorClose(_MODELS[2], save=True)

    def test_save_key_follows_user_keybindings(self) -> None:
        manager = KeybindingsManager({"app.models.save": "ctrl+x"})
        selector = _model_selector(manager=manager)
        assert selector.handle_key("ctrl-x") == SearchSelectorClose(
            _MODELS[2], save=True
        )
        assert "Ctrl+X to set as default" in "".join(selector.render(80, _PLAIN))

    def test_escape_and_ctrl_c_cancel(self) -> None:
        assert _feed(_model_selector(), ["esc"]) == SearchSelectorClose(None)
        assert _feed(_model_selector(), ["ctrl-c"]) == SearchSelectorClose(None)

    def test_navigation_wraps(self) -> None:
        selector = _model_selector()
        selector.handle_key("up")
        assert selector.selected_index == len(_MODELS) - 1
        selector.handle_key("down")
        assert selector.selected_index == 0

    def test_empty_list_ignores_navigation_and_enter(self) -> None:
        selector = _model_selector(search="zzzz")
        assert _feed(selector, ["up", "down", "enter", "ctrl-s"]) is None
        assert selector.filtered() == ()

    def test_tab_without_scoped_models_does_nothing(self) -> None:
        selector = _model_selector()
        selector.handle_key("tab")
        assert selector.scope == "all"

    def test_scoped_list_keeps_pattern_order_and_tab_toggles(self) -> None:
        # Scoped rows keep resolveModelScope order (the enabledModels order),
        # not the all-list sort.
        selector = _model_selector(scoped=[_MODELS[5], _MODELS[0]])
        assert selector.scope == "scoped"
        assert selector.filtered() == (_MODELS[5], _MODELS[0])
        selector.handle_key("tab")
        assert selector.scope == "all"
        assert selector.filtered()[0] == _MODELS[2]  # the current model first
        assert selector.selected_index == 0

    def test_typing_filters_and_resets_the_selection(self) -> None:
        selector = _model_selector()
        selector.handle_key("down")
        _feed(selector, list("sonnet"))
        assert selector.filtered() == (_MODELS[1],)
        assert selector.selected_index == 0
        selector.handle_key("ctrl-u")
        assert selector.query == ""
        assert len(selector.filtered()) == len(_MODELS)

    def test_default_query_puts_the_default_first(self) -> None:
        selector = _model_selector(search="defa")
        assert selector.filtered()[0] == _MODELS[3]

    def test_paste_goes_to_the_search(self) -> None:
        selector = _model_selector()
        selector.paste("opus\n")
        assert selector.query == "opus"
        # Pi ranks sonnet first here too (see `model_typed_down`).
        assert selector.filtered() == (_MODELS[1], _MODELS[3])


class TestThinkingSelectorKeys:
    def test_filter_keeps_the_selected_level(self) -> None:
        selector = _thinking_selector()
        _feed(selector, ["h"])
        assert selector.selected_value() == "high"

    def test_save_enter_escape(self) -> None:
        assert _feed(_thinking_selector(), ["up", "ctrl-s"]) == SearchSelectorClose(
            "medium", save=True
        )
        assert _feed(_thinking_selector(), ["enter"]) == SearchSelectorClose("high")
        assert _feed(_thinking_selector(), ["esc"]) == SearchSelectorClose(None)

    def test_no_match_selects_nothing(self) -> None:
        selector = _thinking_selector()
        assert _feed(selector, ["z", "z", "enter", "ctrl-s"]) is None


def test_model_search_texts_match_pi() -> None:
    choice = ModelChoice("openai", "gpt-5.5", "GPT-5.5")
    assert model_search_text(choice) == (
        "gpt-5.5 openai openai/gpt-5.5 openai gpt-5.5 GPT-5.5"
    )
    assert model_selector_search_text(choice) == (
        "openai openai/gpt-5.5 openai gpt-5.5 GPT-5.5"
    )
    assert model_selector_search_text(ModelChoice("p", "m", "")) == "p p/m p m"


class TestSearchInput:
    def test_editing_keys(self) -> None:
        field = SearchInput()
        for key in "abcd":
            field.handle_key(key)
        field.handle_key("left")
        field.handle_key("left")
        field.handle_key("backspace")
        assert (field.value, field.cursor) == ("acd", 1)
        field.handle_key("ctrl-k")
        assert field.value == "a"
        field.handle_key("home")
        field.handle_key("x")
        field.handle_key("end")
        assert (field.value, field.cursor) == ("xa", 2)
        field.handle_key("ctrl-u")
        assert (field.value, field.cursor) == ("", 0)
        assert field.handle_key("tab") is False

    def test_render_scrolls_around_the_cursor(self) -> None:
        field = SearchInput("abcdefghijkl")
        # Width 10: prompt 2, 8 columns; the cursor at the end reserves one.
        assert field.render(10, _PLAIN) == "> fghijkl "
        field.handle_key("home")
        assert field.render(10, _PLAIN) == "> abcdefgh"
        assert SearchInput("ab").render(6, _PLAIN) == "> ab  "


def test_select_list_scroll_indicator_and_empty_text() -> None:
    items = [SelectItem(str(i), f"item{i}") for i in range(8)]
    select_list = SelectList(items, 3)
    select_list.set_selected_index(4)
    assert _text(select_list.render(40, _PLAIN)) == [
        "  item3",
        "→ item4",
        "  item5",
        "  (5/8)",
    ]
    assert _text(SelectList([], 3).render(40, _PLAIN)) == ["  No matching commands"]


def test_region_lines_put_the_footer_below_the_selector() -> None:
    overlays = OverlayState()
    overlays.begin_search_selector(_thinking_selector())
    lines = search_selector_region_lines(
        overlays, width=80, height=40, footer_lines=("foot1", "foot2"), style=_PLAIN
    )
    assert [line.text for line in lines[-2:]] == ["foot1", "foot2"]
    assert _SGR.sub("", lines[2].text).rstrip() == "Thinking Level"
    overlays.end_search_selector()
    assert overlays.active is None
    assert overlays.search_selector is None
