"""Public Pipy extension API surface.

This is the stable import path for Python extensions (the path the
extension examples in `docs/extension-api.md` import from). It re-exports
the activation-time API and the discovery/activation value objects from
the pipy-owned native runtime, so extension authors depend on
`pipy_harness.extensions` rather than internal module layout.

    from pipy_harness.extensions import PipyExtensionAPI

    def activate(api: PipyExtensionAPI) -> None:
        api.register_command("hello", "Print a greeting", _hello)

The activation API supports command and keyboard-shortcut registration
(`register_command`, `register_shortcut`), event hooks (`on`), tool and
provider registration (`register_tool`, `register_provider` /
`unregister_provider`), and `send_user_message`. Command/shortcut handlers
receive a mode-aware context exposing the workspace root, `ui` (`notify` and
`custom` interactive overlays, simple dialogs, and a multi-line `editor`), a
read-only `conversation` view
(`last_assistant_message`), and a bounded `complete(system_prompt, user_text)`
one-shot completion.
"""

from __future__ import annotations

from pipy_harness.native.extension_runtime import (
    ActivatedExtension,
    AssistantMessageView,
    CommandContext,
    CompletionFn,
    ConversationView,
    CustomComponent,
    CustomComponentFactory,
    ExtensionCapabilityError,
    ExtensionCommandDispatch,
    ExtensionUi,
    PipyExtensionAPI,
    BeforeAgentStartEvent,
    BeforeAgentStartResult,
    ChromeComponent,
    ExtensionProvider,
    ExtensionOAuthConfig,
    ExtensionFlag,
    ExtensionTool,
    ExtensionUiDriver,
    FooterData,
    InputEvent,
    InputTransform,
    LifecycleEvent,
    MessageRenderComponent,
    MessageRenderContext,
    QueuedUserMessage,
    QueuedCustomMessage,
    RegisteredCommand,
    RegisteredMessageRenderer,
    RenderedCustomEntry,
    RegisteredShortcut,
    SessionEntryView,
    SessionHeaderView,
    SessionManagerView,
    SessionTreeNodeView,
    RegisteredFlag,
    ProviderContext,
    RegisteredProvider,
    RegisteredTool,
    dispatch_extension_shortcut,
    extension_shortcuts,
    extension_message_renderers,
    normalize_shortcut_key,
    ThemeColor,
    ToolBlock,
    ToolCallEvent,
    ToolRenderComponent,
    ToolRenderContext,
    ToolRenderTheme,
    ToolResult,
    ToolResultEvent,
    ToolResultTransform,
    BeforeProviderRequestEvent,
    ProviderRequestTransform,
    SessionBeforeEvent,
    SessionDecision,
    UserBashDecision,
    UserBashDispatch,
    UserBashEvent,
    WidgetPlacement,
    activate_extensions,
    coerce_tool_render_lines,
    dispatch_before_provider_request_hooks,
    dispatch_before_agent_start_hooks,
    dispatch_extension_command,
    dispatch_input_hooks,
    dispatch_lifecycle_hooks,
    dispatch_session_before_hooks,
    dispatch_tool_call_hooks,
    dispatch_tool_result_hooks,
    dispatch_user_bash_hooks,
    drain_user_messages,
    drain_custom_messages,
    extension_command_map,
    extension_event_hooks,
    extension_tool_call_hooks,
    build_extension_provider_port,
    extension_providers,
    extension_flags,
    extension_tools,
    lines_component,
    render_extension_message,
    coerce_custom_message,
    safe_custom_entry_data,
    extension_unregistered_providers,
    safe_activation_metadata,
)
from pipy_harness.native.extensions import (
    ExtensionDescriptor,
    discover_extensions,
    safe_extension_metadata,
)

__all__ = [
    "PipyExtensionAPI",
    "CommandContext",
    "ConversationView",
    "AssistantMessageView",
    "SessionEntryView",
    "SessionHeaderView",
    "SessionManagerView",
    "SessionTreeNodeView",
    "CompletionFn",
    "CustomComponent",
    "CustomComponentFactory",
    "ExtensionCapabilityError",
    "ExtensionUi",
    "ExtensionUiDriver",
    "ChromeComponent",
    "FooterData",
    "WidgetPlacement",
    "MessageRenderComponent",
    "MessageRenderContext",
    "RenderedCustomEntry",
    "RegisteredCommand",
    "RegisteredMessageRenderer",
    "ActivatedExtension",
    "ExtensionCommandDispatch",
    "ToolBlock",
    "ToolCallEvent",
    "LifecycleEvent",
    "InputEvent",
    "InputTransform",
    "BeforeAgentStartEvent",
    "BeforeAgentStartResult",
    "QueuedUserMessage",
    "QueuedCustomMessage",
    "ExtensionTool",
    "ExtensionProvider",
    "ExtensionOAuthConfig",
    "ExtensionFlag",
    "ProviderContext",
    "RegisteredProvider",
    "RegisteredFlag",
    "ToolResult",
    "RegisteredTool",
    "ToolResultEvent",
    "ToolResultTransform",
    "BeforeProviderRequestEvent",
    "ProviderRequestTransform",
    "SessionBeforeEvent",
    "SessionDecision",
    "UserBashDecision",
    "UserBashDispatch",
    "UserBashEvent",
    "RegisteredShortcut",
    "dispatch_extension_shortcut",
    "extension_shortcuts",
    "extension_message_renderers",
    "normalize_shortcut_key",
    "ThemeColor",
    "ToolRenderComponent",
    "ToolRenderContext",
    "ToolRenderTheme",
    "coerce_tool_render_lines",
    "lines_component",
    "dispatch_tool_result_hooks",
    "dispatch_user_bash_hooks",
    "dispatch_before_provider_request_hooks",
    "dispatch_session_before_hooks",
    "extension_tools",
    "extension_providers",
    "extension_flags",
    "extension_unregistered_providers",
    "render_extension_message",
    "coerce_custom_message",
    "safe_custom_entry_data",
    "build_extension_provider_port",
    "activate_extensions",
    "dispatch_extension_command",
    "extension_command_map",
    "extension_tool_call_hooks",
    "extension_event_hooks",
    "dispatch_tool_call_hooks",
    "dispatch_lifecycle_hooks",
    "dispatch_input_hooks",
    "dispatch_before_agent_start_hooks",
    "drain_user_messages",
    "drain_custom_messages",
    "safe_activation_metadata",
    "ExtensionDescriptor",
    "discover_extensions",
    "safe_extension_metadata",
]
