"""Static built-in model catalog data (pipy-owned).

This is the pipy analogue of Pi's generated ``models.generated.ts`` table, kept
hand-authored and deliberately smaller: it covers every provider pipy
implements with a real adapter, carrying multiple rows per provider (aliases +
dated versions + a default) so pattern matching, ``--list-models`` and the
``/model`` selector are useful. It does not need to be byte-identical to Pi's
table, but every row Pi also ships carries Pi's generated cost, context window,
max tokens and thinking map (``packages/ai/scripts/generate-models.ts``).

Pi thinking maps that are PARTIAL (they omit an ordinary level Pi treats as
identity-supported) are spelled out here, because pipy's ``map_thinking_level``
derives support from map keys. A Pi ``null`` stays ``None``; a key Pi omits stays
omitted — this matters for ``off``: an absent ``off`` means the Responses
off-state sends ``"none"`` and Anthropic sends ``thinking:{type:"disabled"}``,
while ``off: None`` means thinking cannot be switched off (the level is not
offered and no off-state field is sent).

ds4 is intentionally absent: it is a ``models.json`` custom provider, not a
built-in row. ``fake`` is the deterministic bootstrap.

``api`` values map onto existing ``ProviderPort`` adapter families:
  anthropic-messages, openai-responses, openai-codex-responses,
  openai-completions, google-generative-ai, google-vertex, amazon-bedrock,
  azure-openai-responses, cloudflare-workers-ai, mistral, fake.
"""

from __future__ import annotations

from collections.abc import Mapping

from pipy_harness.native.catalog import (
    ContextWindowSource,
    NativeModelCost,
    NativeModelSpec,
)

# Default per-provider base URLs. Pi's catalog rows always carry a baseUrl, and
# the models.json custom-model parser skips a row whose baseUrl cannot be
# resolved (Pi: ``if (!baseUrl) continue``), so every built-in provider must
# supply one for inherited custom models to resolve.
_PROVIDER_BASE_URL: dict[str, str] = {
    "anthropic": "https://api.anthropic.com",
    "openai": "https://api.openai.com/v1",
    "openai-completions": "https://api.openai.com/v1",
    "openai-codex": "https://chatgpt.com/backend-api/codex",
    "openrouter": "https://openrouter.ai/api/v1",
    "google": "https://generativelanguage.googleapis.com",
    "google-vertex": "https://aiplatform.googleapis.com",
    "mistral": "https://api.mistral.ai/v1",
    "amazon-bedrock": "https://bedrock-runtime.us-east-1.amazonaws.com",
    # Azure resource root; the adapter normalizes Azure hosts to /openai/v1 and
    # appends /responses?api-version=v1 (deployment carried as the body model).
    "azure-openai": "https://azure-openai.example",
    # Cloudflare embeds the account id via a {ENV} placeholder (Pi-style);
    # construction substitutes it and appends /chat/completions.
    "cloudflare": "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1",
}


def _m(
    provider: str,
    model_id: str,
    display_name: str,
    api: str,
    *,
    base_url: str | None = None,
    reasoning: bool = False,
    thinking: Mapping[str, str | None] | None = None,
    image: bool = False,
    cost: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0),
    context_window: int = 128_000,
    max_tokens: int = 16_384,
    compat: Mapping[str, object] | None = None,
) -> NativeModelSpec:
    return NativeModelSpec(
        provider_name=provider,
        model_id=model_id,
        display_name=display_name,
        api=api,
        base_url=base_url or _PROVIDER_BASE_URL.get(provider),
        reasoning=reasoning,
        thinking_level_map=dict(thinking or {}),
        input=("text", "image") if image else ("text",),
        cost=NativeModelCost(
            input=cost[0], output=cost[1], cache_read=cost[2], cache_write=cost[3]
        ),
        context_window=context_window,
        context_window_source=ContextWindowSource.BUILTIN,
        max_tokens=max_tokens,
        compat=dict(compat) if compat is not None else None,
    )


_ANTHROPIC_URL = "https://api.anthropic.com"
# Legacy pipy-only rows (not in Pi's current table) keep their original maps.
_REASONING_LEVELS = {
    "off": None,
    "minimal": "minimal",
    "low": "low",
    "medium": "medium",
    "high": "high",
}
_ORDINARY_IDENTITY: dict[str, str | None] = {
    "minimal": "minimal",
    "low": "low",
    "medium": "medium",
    "high": "high",
}
# ---- Anthropic (adaptive Claude) -------------------------------------------
# Pi generate-models.ts:1080-1094 merges {xhigh, max} for opus-4-7+/opus-5/
# sonnet-5, and {off: null, xhigh, max} for fable-5.
_CLAUDE_XHIGH_MAX = {**_ORDINARY_IDENTITY, "xhigh": "xhigh", "max": "max"}
_CLAUDE_NO_OFF_XHIGH_MAX = {"off": None, **_CLAUDE_XHIGH_MAX}
# Opus/Sonnet 5.5: Pi's full map (models.dev effort options).
_CLAUDE_5_5 = {
    "off": None,
    "minimal": None,
    "low": "low",
    "medium": "medium",
    "high": "high",
    "xhigh": "xhigh",
    "max": "max",
}
_CLAUDE_MAX_ONLY = {**_ORDINARY_IDENTITY, "max": "max"}
_ADAPTIVE = {"forceAdaptiveThinking": True}
# ---- OpenAI Responses (api.openai.com) -------------------------------------
_OPENAI_GPT_5_5 = {
    "off": "none",
    "minimal": None,
    "low": "low",
    "medium": "medium",
    "high": "high",
    "xhigh": "xhigh",
    "max": None,
}
_OPENAI_GPT_MAX = {**_OPENAI_GPT_5_5, "max": "max"}
_OPENAI_GPT_6_ASTRA = {**_OPENAI_GPT_MAX, "off": None}
# ---- OpenAI Codex (chatgpt.com) --------------------------------------------
# Pi merges {minimal: "low"} into every xhigh-capable Codex row
# (generate-models.ts:1120); no `off` key means the off-state sends "none".
_CODEX_XHIGH = {
    "minimal": "low",
    "low": "low",
    "medium": "medium",
    "high": "high",
    "xhigh": "xhigh",
}
_CODEX_XHIGH_MAX = {**_CODEX_XHIGH, "max": "max"}
_CODEX_GPT_6 = {"off": "none", **_CODEX_XHIGH_MAX}
_CODEX_GPT_6_ASTRA = {**_CODEX_GPT_6, "off": None}
# ---- Google Gemini 3.x -----------------------------------------------------
_GEMINI_3_FLASH = {
    "off": None,
    "minimal": "minimal",
    "low": "low",
    "medium": "medium",
    "high": "high",
    "xhigh": None,
    "max": None,
}
_GEMINI_3_PRO = {**_GEMINI_3_FLASH, "minimal": None}
_OPENAI_TOOLS = {"supportsToolSearch": True}


BUILTIN_MODEL_ROWS: tuple[NativeModelSpec, ...] = (
    # ---- anthropic (anthropic-messages) -------------------------------------
    _m(
        "anthropic",
        "claude-opus-5-5",
        "Claude Opus 5.5",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_5_5,
        image=True,
        compat=_ADAPTIVE,
        cost=(4.0, 20.0, 0.2, 5.0),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-sonnet-5-5",
        "Claude Sonnet 5.5",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_5_5,
        image=True,
        compat=_ADAPTIVE,
        cost=(2.0, 10.0, 0.2, 2.5),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-fable-5-1",
        "Claude Fable 5.1",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_NO_OFF_XHIGH_MAX,
        image=True,
        compat=_ADAPTIVE,
        cost=(10.0, 50.0, 0.25, 12.5),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-fable-5",
        "Claude Fable 5",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_NO_OFF_XHIGH_MAX,
        image=True,
        compat=_ADAPTIVE,
        cost=(10.0, 50.0, 1.0, 12.5),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-opus-5",
        "Claude Opus 5",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_NO_OFF_XHIGH_MAX,
        image=True,
        compat=_ADAPTIVE,
        cost=(5.0, 25.0, 0.5, 6.25),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-sonnet-5",
        "Claude Sonnet 5",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_XHIGH_MAX,
        image=True,
        compat=_ADAPTIVE,
        cost=(2.0, 10.0, 0.2, 2.5),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-opus-4-8",
        "Claude Opus 4.8",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_XHIGH_MAX,
        image=True,
        compat=_ADAPTIVE,
        cost=(5.0, 25.0, 0.5, 6.25),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-opus-4-7",
        "Claude Opus 4.7",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        thinking=_CLAUDE_XHIGH_MAX,
        image=True,
        compat=_ADAPTIVE,
        cost=(5.0, 25.0, 0.5, 6.25),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "anthropic",
        "claude-sonnet-4-5",
        "Claude Sonnet 4.5",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        image=True,
        cost=(3.0, 15.0, 0.3, 3.75),
        context_window=1_000_000,
        max_tokens=64_000,
    ),
    _m(
        "anthropic",
        "claude-sonnet-4-5-20250929",
        "Claude Sonnet 4.5 (2025-09-29)",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        image=True,
        cost=(3.0, 15.0, 0.3, 3.75),
        context_window=1_000_000,
        max_tokens=64_000,
    ),
    _m(
        "anthropic",
        "claude-haiku-4-5",
        "Claude Haiku 4.5 (latest)",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        image=True,
        cost=(1.0, 5.0, 0.1, 1.25),
        context_window=200_000,
        max_tokens=64_000,
    ),
    _m(
        "anthropic",
        "claude-haiku-4-5-20251001",
        "Claude Haiku 4.5",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        reasoning=True,
        image=True,
        cost=(1.0, 5.0, 0.1, 1.25),
        context_window=200_000,
        max_tokens=64_000,
    ),
    _m(
        "anthropic",
        "claude-3-5-sonnet-latest",
        "Claude 3.5 Sonnet (latest)",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        image=True,
        cost=(3.0, 15.0, 0.3, 3.75),
        context_window=200_000,
        max_tokens=8_192,
    ),
    _m(
        "anthropic",
        "claude-3-5-sonnet-20241022",
        "Claude 3.5 Sonnet (2024-10-22)",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        image=True,
        cost=(3.0, 15.0, 0.3, 3.75),
        context_window=200_000,
        max_tokens=8_192,
    ),
    _m(
        "anthropic",
        "claude-3-5-haiku-20241022",
        "Claude 3.5 Haiku (2024-10-22)",
        "anthropic-messages",
        base_url=_ANTHROPIC_URL,
        cost=(0.8, 4.0, 0.08, 1.0),
        context_window=200_000,
        max_tokens=8_192,
    ),
    # ---- openai (openai-responses) ------------------------------------------
    _m(
        "openai",
        "gpt-6-sol",
        "GPT-6 Sol",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_MAX,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(2.0, 10.0, 0.2, 2.5),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-6-luna",
        "GPT-6 Luna",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_MAX,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(0.1, 0.5, 0.01, 0.125),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-6-astra",
        "GPT-6 Astra",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_6_ASTRA,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(10.0, 50.0, 1.0, 12.5),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-5.6-sol",
        "GPT-5.6 Sol",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_MAX,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(4.0, 20.0, 0.4, 5.0),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-5.6-terra",
        "GPT-5.6 Terra",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_MAX,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(2.0, 12.0, 0.2, 2.5),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-5.6-luna",
        "GPT-5.6 Luna",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_MAX,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(0.2, 1.2, 0.02, 0.25),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-5.5",
        "GPT-5.5",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_5_5,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(5.0, 30.0, 0.5, 0.0),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-5.4",
        "GPT-5.4",
        "openai-responses",
        reasoning=True,
        thinking=_OPENAI_GPT_5_5,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(2.5, 15.0, 0.25, 0.0),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-5.1-codex",
        "GPT-5.1 Codex",
        "openai-responses",
        reasoning=True,
        thinking=_REASONING_LEVELS,
        image=True,
        cost=(1.25, 10.0, 0.125, 0.0),
        context_window=400_000,
        max_tokens=128_000,
    ),
    _m(
        "openai",
        "gpt-4o",
        "GPT-4o",
        "openai-responses",
        image=True,
        cost=(2.5, 10.0, 1.25, 0.0),
        context_window=128_000,
        max_tokens=16_384,
    ),
    _m(
        "openai",
        "gpt-4o-mini",
        "GPT-4o mini",
        "openai-responses",
        image=True,
        cost=(0.15, 0.6, 0.075, 0.0),
        context_window=128_000,
        max_tokens=16_384,
    ),
    # ---- openai-codex (openai-codex-responses) ------------------------------
    # Pi's Codex rows are all 272K context / 128K output; Pi retired the Codex
    # gpt-5.4 rows (2e6fe2f98), so pipy does not carry one.
    _m(
        "openai-codex",
        "gpt-6-sol",
        "GPT-6 Sol (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_CODEX_GPT_6,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(2.0, 10.0, 0.2, 2.5),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai-codex",
        "gpt-6-luna",
        "GPT-6 Luna (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_CODEX_GPT_6,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(0.1, 0.5, 0.01, 0.125),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai-codex",
        "gpt-6-astra",
        "GPT-6 Astra (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_CODEX_GPT_6_ASTRA,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(10.0, 50.0, 1.0, 12.5),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai-codex",
        "gpt-5.5",
        "GPT-5.5 (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_CODEX_XHIGH,
        image=True,
        compat=_OPENAI_TOOLS,
        cost=(5.0, 30.0, 0.5, 0.0),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai-codex",
        "gpt-5.1-codex",
        "GPT-5.1 Codex (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_REASONING_LEVELS,
        image=True,
        context_window=400_000,
        max_tokens=128_000,
    ),
    # Codex thinking maps differ per row: gpt-5.5 maps xhigh but not max, the
    # GPT-5.6 and GPT-6 rows map both, and gpt-5.1-codex maps only the ordinary
    # tier. So a stored `max` clamps to xhigh on gpt-5.5 and to high on
    # gpt-5.1-codex.
    _m(
        "openai-codex",
        "gpt-5.6-sol",
        "GPT-5.6 Sol (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_CODEX_XHIGH_MAX,
        compat=_OPENAI_TOOLS,
        image=True,
        cost=(4.0, 20.0, 0.4, 5.0),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai-codex",
        "gpt-5.6-terra",
        "GPT-5.6 Terra (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_CODEX_XHIGH_MAX,
        compat=_OPENAI_TOOLS,
        image=True,
        cost=(2.0, 12.0, 0.2, 2.5),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai-codex",
        "gpt-5.6-luna",
        "GPT-5.6 Luna (Codex/ChatGPT)",
        "openai-codex-responses",
        reasoning=True,
        thinking=_CODEX_XHIGH_MAX,
        compat=_OPENAI_TOOLS,
        image=True,
        cost=(0.2, 1.2, 0.02, 0.25),
        context_window=272_000,
        max_tokens=128_000,
    ),
    # ---- openai-completions (openai-completions) ----------------------------
    # pipy-only provider name for OpenAI Chat Completions. Pi has no such
    # provider, so its default mirrors Pi's `openai` default (gpt-5.5) and the
    # row copies Pi's openai gpt-5.5 metadata.
    _m(
        "openai-completions",
        "gpt-5.5",
        "GPT-5.5 (Completions)",
        "openai-completions",
        reasoning=True,
        thinking=_OPENAI_GPT_5_5,
        image=True,
        cost=(5.0, 30.0, 0.5, 0.0),
        context_window=272_000,
        max_tokens=128_000,
    ),
    _m(
        "openai-completions",
        "gpt-4o-mini",
        "GPT-4o mini (Completions)",
        "openai-completions",
        image=True,
        cost=(0.15, 0.6, 0.075, 0.0),
        context_window=128_000,
        max_tokens=16_384,
    ),
    _m(
        "openai-completions",
        "gpt-4o",
        "GPT-4o (Completions)",
        "openai-completions",
        image=True,
        cost=(2.5, 10.0, 1.25, 0.0),
        context_window=128_000,
        max_tokens=16_384,
    ),
    _m(
        "openai-completions",
        "gpt-4.1",
        "GPT-4.1 (Completions)",
        "openai-completions",
        image=True,
        cost=(2.0, 8.0, 0.5, 0.0),
        context_window=1_000_000,
        max_tokens=32_768,
    ),
    # ---- openrouter (openai-completions) ------------------------------------
    # Pi routes OpenRouter `anthropic/claude-*` rows through anthropic-messages
    # (openrouter.ai/api + session-affinity headers); pipy's openrouter rows are
    # openai-completions only, so no Claude 5.x OpenRouter rows are mirrored yet.
    _m(
        "openrouter",
        "openai/gpt-5.1-codex",
        "OpenRouter: GPT-5.1 Codex",
        "openai-completions",
        base_url="https://openrouter.ai/api/v1",
        reasoning=True,
        image=True,
        context_window=400_000,
        max_tokens=128_000,
    ),
    _m(
        "openrouter",
        "anthropic/claude-opus-4-7",
        "OpenRouter: Claude Opus 4.7",
        "openai-completions",
        base_url="https://openrouter.ai/api/v1",
        reasoning=True,
        image=True,
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "openrouter",
        "moonshotai/kimi-k2.6",
        "OpenRouter: Kimi K2.6",
        "openai-completions",
        base_url="https://openrouter.ai/api/v1",
        reasoning=True,
        image=True,
        cost=(0.65, 3.41, 0.15, 0.0),
        context_window=262_144,
        max_tokens=235_929,
    ),
    _m(
        "openrouter",
        "openai/gpt-4o:extended",
        "OpenRouter: GPT-4o (extended)",
        "openai-completions",
        base_url="https://openrouter.ai/api/v1",
        image=True,
        context_window=128_000,
        max_tokens=64_000,
    ),
    # ---- google (google-generative-ai) --------------------------------------
    _m(
        "google",
        "gemini-3.1-pro-preview",
        "Gemini 3.1 Pro (preview)",
        "google-generative-ai",
        reasoning=True,
        thinking=_GEMINI_3_PRO,
        image=True,
        cost=(2.0, 12.0, 0.2, 0.0),
        context_window=1_048_576,
        max_tokens=65_536,
    ),
    _m(
        "google",
        "gemini-3.5-flash",
        "Gemini 3.5 Flash",
        "google-generative-ai",
        reasoning=True,
        thinking=_GEMINI_3_FLASH,
        image=True,
        cost=(1.5, 9.0, 0.15, 0.0),
        context_window=1_048_576,
        max_tokens=65_536,
    ),
    _m(
        "google",
        "gemini-3.1-flash-lite",
        "Gemini 3.1 Flash Lite",
        "google-generative-ai",
        reasoning=True,
        thinking=_GEMINI_3_FLASH,
        image=True,
        cost=(0.25, 1.5, 0.025, 0.0),
        context_window=1_048_576,
        max_tokens=65_536,
    ),
    _m(
        "google",
        "gemini-2.5-pro",
        "Gemini 2.5 Pro",
        "google-generative-ai",
        reasoning=True,
        image=True,
        cost=(1.25, 10.0, 0.0, 0.0),
        context_window=1_000_000,
        max_tokens=65_536,
    ),
    _m(
        "google",
        "gemini-2.0-flash-exp",
        "Gemini 2.0 Flash (exp)",
        "google-generative-ai",
        image=True,
        context_window=1_000_000,
        max_tokens=8_192,
    ),
    # ---- google-vertex (google-vertex) --------------------------------------
    # Pi ships no Claude rows on Vertex, so none are mirrored here.
    _m(
        "google-vertex",
        "gemini-3.1-pro-preview",
        "Vertex: Gemini 3.1 Pro (preview)",
        "google-vertex",
        reasoning=True,
        thinking=_GEMINI_3_PRO,
        image=True,
        cost=(2.0, 12.0, 0.2, 0.0),
        context_window=1_048_576,
        max_tokens=65_536,
    ),
    _m(
        "google-vertex",
        "gemini-3.5-flash",
        "Vertex: Gemini 3.5 Flash",
        "google-vertex",
        reasoning=True,
        thinking=_GEMINI_3_FLASH,
        image=True,
        cost=(1.5, 9.0, 0.15, 0.0),
        context_window=1_048_576,
        max_tokens=65_536,
    ),
    _m(
        "google-vertex",
        "gemini-3.1-flash-lite",
        "Vertex: Gemini 3.1 Flash Lite",
        "google-vertex",
        reasoning=True,
        thinking=_GEMINI_3_FLASH,
        image=True,
        cost=(0.25, 1.5, 0.025, 0.0),
        context_window=1_048_576,
        max_tokens=65_536,
    ),
    _m(
        "google-vertex",
        "gemini-2.5-pro",
        "Vertex: Gemini 2.5 Pro",
        "google-vertex",
        reasoning=True,
        image=True,
        context_window=1_000_000,
        max_tokens=65_536,
    ),
    _m(
        "google-vertex",
        "gemini-2.0-flash-001",
        "Vertex: Gemini 2.0 Flash",
        "google-vertex",
        image=True,
        context_window=1_000_000,
        max_tokens=8_192,
    ),
    # ---- mistral (mistral) ---------------------------------------------------
    _m(
        "mistral",
        "mistral-large-latest",
        "Mistral Large (latest)",
        "mistral",
        cost=(2.0, 6.0, 0.0, 0.0),
        context_window=131_072,
        max_tokens=32_768,
    ),
    _m(
        "mistral",
        "devstral-medium-latest",
        "Devstral Medium (latest)",
        "mistral",
        cost=(0.4, 2.0, 0.0, 0.0),
        context_window=131_072,
        max_tokens=32_768,
    ),
    _m(
        "mistral",
        "mistral-small-latest",
        "Mistral Small (latest)",
        "mistral",
        cost=(0.2, 0.6, 0.0, 0.0),
        context_window=131_072,
        max_tokens=32_768,
    ),
    # ---- amazon-bedrock (amazon-bedrock) ------------------------------------
    # Pi's `us.` inference-profile rows (US pricing). Pi merges {xhigh, max}
    # into the opus-5/sonnet-5 rows and {off: null, xhigh, max} into fable-5.
    _m(
        "amazon-bedrock",
        "us.anthropic.claude-opus-4-6-v1",
        "Bedrock: Claude Opus 4.6",
        "amazon-bedrock",
        reasoning=True,
        thinking=_CLAUDE_MAX_ONLY,
        image=True,
        cost=(5.5, 27.5, 0.55, 6.875),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "amazon-bedrock",
        "us.anthropic.claude-opus-5-5",
        "Bedrock: Claude Opus 5.5 (US)",
        "amazon-bedrock",
        reasoning=True,
        thinking=_CLAUDE_XHIGH_MAX,
        image=True,
        cost=(4.4, 22.0, 0.22, 5.5),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "amazon-bedrock",
        "us.anthropic.claude-opus-5",
        "Bedrock: Claude Opus 5 (US)",
        "amazon-bedrock",
        reasoning=True,
        thinking=_CLAUDE_XHIGH_MAX,
        image=True,
        cost=(5.5, 27.5, 0.55, 6.875),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "amazon-bedrock",
        "us.anthropic.claude-sonnet-5",
        "Bedrock: Claude Sonnet 5 (US)",
        "amazon-bedrock",
        reasoning=True,
        thinking=_CLAUDE_XHIGH_MAX,
        image=True,
        cost=(2.2, 11.0, 0.22, 2.75),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "amazon-bedrock",
        "us.anthropic.claude-fable-5",
        "Bedrock: Claude Fable 5 (US)",
        "amazon-bedrock",
        reasoning=True,
        thinking=_CLAUDE_NO_OFF_XHIGH_MAX,
        image=True,
        cost=(11.0, 55.0, 1.1, 13.75),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "amazon-bedrock",
        "us.anthropic.claude-opus-4-8",
        "Bedrock: Claude Opus 4.8 (US)",
        "amazon-bedrock",
        reasoning=True,
        thinking=_CLAUDE_XHIGH_MAX,
        image=True,
        cost=(5.5, 27.5, 0.55, 6.875),
        context_window=1_000_000,
        max_tokens=128_000,
    ),
    _m(
        "amazon-bedrock",
        "us.anthropic.claude-haiku-4-5-20251001-v1:0",
        "Bedrock: Claude Haiku 4.5 (US)",
        "amazon-bedrock",
        reasoning=True,
        image=True,
        cost=(1.1, 5.5, 0.11, 1.375),
        context_window=200_000,
        max_tokens=64_000,
    ),
    _m(
        "amazon-bedrock",
        "anthropic.claude-3-5-sonnet-20241022-v2:0",
        "Bedrock: Claude 3.5 Sonnet v2",
        "amazon-bedrock",
        image=True,
        cost=(3.0, 15.0, 0.3, 3.75),
        context_window=200_000,
        max_tokens=8_192,
    ),
    _m(
        "amazon-bedrock",
        "anthropic.claude-3-5-sonnet-20240620-v1:0",
        "Bedrock: Claude 3.5 Sonnet v1",
        "amazon-bedrock",
        image=True,
        cost=(3.0, 15.0, 0.3, 3.75),
        context_window=200_000,
        max_tokens=8_192,
    ),
    # ---- azure-openai (azure-openai-responses) ------------------------------
    _m(
        "azure-openai",
        "gpt-5.4",
        "Azure: GPT-5.4",
        "azure-openai-responses",
        reasoning=True,
        # Pi: {off: null, xhigh: "xhigh"} — thinking cannot be switched off.
        thinking={"off": None, **_ORDINARY_IDENTITY, "xhigh": "xhigh"},
        image=True,
        cost=(2.5, 15.0, 0.25, 0.0),
        context_window=1_050_000,
        max_tokens=128_000,
    ),
    _m(
        "azure-openai",
        "gpt-4o",
        "Azure: GPT-4o",
        "azure-openai-responses",
        image=True,
        cost=(2.5, 10.0, 1.25, 0.0),
        context_window=128_000,
        max_tokens=16_384,
    ),
    _m(
        "azure-openai",
        "gpt-4o-mini",
        "Azure: GPT-4o mini",
        "azure-openai-responses",
        image=True,
        cost=(0.15, 0.6, 0.075, 0.0),
        context_window=128_000,
        max_tokens=16_384,
    ),
    # ---- cloudflare (cloudflare-workers-ai) ---------------------------------
    _m(
        "cloudflare",
        "@cf/moonshotai/kimi-k2.6",
        "Cloudflare: Kimi K2.6",
        "cloudflare-workers-ai",
        reasoning=True,
        thinking={
            "off": "none",
            "minimal": None,
            "low": None,
            "medium": None,
            "high": "high",
            "xhigh": None,
            "max": None,
        },
        image=True,
        cost=(0.95, 4.0, 0.16, 0.0),
        context_window=262_144,
        max_tokens=256_000,
    ),
    _m(
        "cloudflare",
        "@cf/meta/llama-3.3-70b-instruct",
        "Cloudflare: Llama 3.3 70B",
        "cloudflare-workers-ai",
        context_window=131_072,
        max_tokens=16_384,
    ),
    _m(
        "cloudflare",
        "@cf/meta/llama-3.1-8b-instruct",
        "Cloudflare: Llama 3.1 8B",
        "cloudflare-workers-ai",
        context_window=128_000,
        max_tokens=8_192,
    ),
    # ---- fake (deterministic bootstrap) -------------------------------------
    _m("fake", "fake-native-bootstrap", "Fake (bootstrap)", "fake"),
)
