"""Session recording helpers for pipy."""

from pipy_session.auto_capture import (
    AutoCaptureState,
    HookResult,
    PrunedState,
    append_auto_event,
    handle_claude_hook,
    prune_auto_capture_state,
    reference_pi_session,
    start_auto_capture,
    state_dir,
    stop_auto_capture,
)
from pipy_session.catalog import (
    FinalizedSessionInspection,
    FinalizedSessionListing,
    FinalizedSessionSearchMatch,
    FinalizedSessionSearchResult,
    SessionArchiveVerification,
    VerificationIssue,
    inspect_finalized_session,
    list_finalized_sessions,
    resolve_finalized_record,
    search_finalized_sessions,
    verify_session_archive,
)
from pipy_session.recorder import (
    FILENAME_RE,
    PROJECT_NAME,
    FinalizedRecordError,
    SessionRecord,
    append_event,
    finalize_session,
    init_session,
    resolve_active_path,
    resolve_session_root,
)

__all__ = [
    "PROJECT_NAME",
    "AutoCaptureState",
    "FILENAME_RE",
    "FinalizedRecordError",
    "FinalizedSessionInspection",
    "FinalizedSessionListing",
    "FinalizedSessionSearchMatch",
    "FinalizedSessionSearchResult",
    "HookResult",
    "PrunedState",
    "SessionRecord",
    "SessionArchiveVerification",
    "VerificationIssue",
    "append_auto_event",
    "append_event",
    "finalize_session",
    "handle_claude_hook",
    "init_session",
    "inspect_finalized_session",
    "list_finalized_sessions",
    "prune_auto_capture_state",
    "reference_pi_session",
    "resolve_active_path",
    "resolve_finalized_record",
    "resolve_session_root",
    "search_finalized_sessions",
    "start_auto_capture",
    "state_dir",
    "stop_auto_capture",
    "verify_session_archive",
]
